37myDjango/myDjango/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

39myDjango/myDjango/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('blog.urls'))
    # path('', include('shop.urls'))
    # path('', include('book_shop.urls'))
    path('', include('book_shope.urls'))
]

Flavors/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shope.urls', namespace='shope')),
    path('users/', include('users.urls', namespace='users')),
    # path('users/', include('django.contrib.auth.urls'),),
    path('orders/', include('orders.urls', namespace='orders')),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/add/<int:pk>/', views.add_cart_item, name='add_cart_item'),
    # path('cart/add/<int:pk>/', views.AddCartItem.as_view(), name='add_cart_item'),
    path('cart_update/<int:pk>/', views.update_cart_item, name='update_cart_item'),
    # path('cart_update/<int:pk>/', views.UpdateCartItemView.as_view(), name='update_cart_item'),
    path('cart/delete/<int:pk>/', views.delete_cart_item, name='delete_cart_item'),
    # path('cart/delete/<int:pk>/', views.DeleteCartItemView.as_view(), name='delete_cart_item'),
    path('order/<int:pk>/', views.order_detail_view, name='order_detail'),
    path('orders/', views.list_orders_view, name='orders'),
    path('proceed_to_checkout/', views.ProceedToCheckoutView.as_view(), name='proceed_to_checkout'),


]

shope/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shope'

urlpatterns = [
    path('', views.index, name='index'),
    path('index-cbv/', views.IndexView.as_view(), name='index-cbv'),
    path('product/add/', views.add_product, name='add_product'),
    path('product-cbv/add/', views.AddProductView.as_view(), name='add_product_cbv'),
    path('product/detail/<int:pk>/', views.detail_product, name='detail_product'),
    path('product-cbv/detail/<int:pk>/', views.ProductDetailView.as_view(), name='detail_product_cbv'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

42myDjango/book_shope/forms.py
from django import forms
from .models import Product, Category

class ProductForm(forms.ModelForm):
    
    class Meta():
        model = Product
        # fields = ('name', 'price', 'stock')
        fields = '__all__'
        widgets = {
            'category': forms.CheckboxSelectMultiple(attrs={'class': 'form-control d-flex'}),
            'name': forms.TextInput(attrs={'placeholder': 'Please input a name of product'}),
            'description': forms.Textarea(attrs={'placeholder': 'Please input the description of product'}),
            'price': forms.NumberInput(attrs={'placeholder': 'Please enter a price'}),
            # 'stock': forms.NumberInput(attrs={'placeholder': 'Please enter a product quantity'}),
        }

39myDjango/book_shope/views.py
from django.shortcuts import render
from .models import Category, Product

# Create your views here.
def index(request):
    products = Product.objects.all()
    
    return render(request, 'index.html', {'products': products})

40myDjango/book_shope/views.py
from django.shortcuts import render, redirect
from .models import Category, Product
from django.db.models import Q
from .forms import ProductForm

# Create your views here.
def index(request):
    product_name = request.GET.get('product_name')
    category = request.GET.getlist('category')
    
    
    if product_name:
        products = Product.objects.filter(name__icontains=product_name)
    elif category:
        products = Product.objects.filter(category__in=category)
    else:
        products = Product.objects.all()
    
    
    categories = Category.objects.all()
    category_by_type = {}
    
    for category in categories:
        category_type = category.category_type
        if category_type not in category_by_type:
            category_by_type[category_type] = []
        category_by_type[category_type].append(category)
    
    print(category_by_type)
    
    return render(request, 'index.html', {'products': products, 'categories_by_type': category_by_type})

def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            form.save_m2m()
            return redirect('book_shope:index')
    else:
        form = ProductForm()
        return render(request, 'add_product.html', {'form': form})

41myDjango/book_shope/views.py
from django.shortcuts import render, redirect
from .models import Category, Product
from django.db.models import Q
from .forms import ProductForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.
def index(request):
    product_name = request.GET.get('product_name')
    category = request.GET.getlist('category')
    
    
    if product_name:
        products = Product.objects.filter(name__icontains=product_name)
    elif category:
        products = Product.objects.filter(category__in=category)
    else:
        products = Product.objects.all()
        

    paginator = Paginator(products, 8)

    try:        
        page_number = request.GET.get('page')
    
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    
    
    
    categories = Category.objects.all()
    category_by_type = {}
    
    for category in categories:
        category_type = category.category_type
        if category_type not in category_by_type:
            category_by_type[category_type] = []
        category_by_type[category_type].append(category)
    
    print(category_by_type)
    
    return render(request, 'index.html', {'products': products, 'categories_by_type': category_by_type})

def detail_product(request, pk):
    product = Product.objects.get(pk=pk)
    
    related_products = Product.objects.filter(category__in=product.category.all()).exclude(id=product.id)
    
    return render(request, 'detail_product.html', {'product': product, 'related_products': related_products})
    

    
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            form.save_m2m()
            return redirect('book_shope:index')
    else:
        form = ProductForm()
        return render(request, 'add_product.html', {'form': form})

42myDjango/book_shope/views.py
from django.shortcuts import render, redirect
from .models import Category, Product
from django.db.models import Q
from .forms import ProductForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    product_name = request.GET.get('product_name')
    category = request.GET.getlist('category')
    
    
    if product_name:
        products = Product.objects.filter(name__icontains=product_name)
    elif category:
        products = Product.objects.filter(category__in=category)
    else:
        products = Product.objects.all()
        

    paginator = Paginator(products, 8)

    try:        
        page_number = request.GET.get('page')
    
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    
    
    
    categories = Category.objects.all()
    category_by_type = {}
    
    for category in categories:
        category_type = category.category_type
        if category_type not in category_by_type:
            category_by_type[category_type] = []
        category_by_type[category_type].append(category)
    
    print(category_by_type)
    
    return render(request, 'index.html', {'products': products, 'categories_by_type': category_by_type})


@login_required(login_url='/users/login/')
def detail_product(request, pk):
    product = Product.objects.get(pk=pk)
    
    related_products = Product.objects.filter(category__in=product.category.all()).exclude(id=product.id)
    
    return render(request, 'detail_product.html', {'product': product, 'related_products': related_products})
    

    
def add_product(request):
    if request.user.has_perm('book_shope.add_product'):
        if request.method == 'POST':
            form = ProductForm(request.POST)
            if form.is_valid():
                product = form.save(commit=False)
                product.save()
                form.save_m2m()
                return redirect('book_shope:index')
        else:
            form = ProductForm()
            return render(request, 'add_product.html', {'form': form})
    else:
        return redirect('book_shope:index')

45myDjango/book_shope/views.py
from django.shortcuts import render, redirect
from .models import Category, Product
from .forms import ProductForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
import logging

logger = logging.getLogger(__name__)  # Logger setup

# Create your views here.
def index(request):
    product_name = request.GET.get('product_name')
    category = request.GET.getlist('category')
    
    if product_name:
        products = Product.objects.filter(name__icontains=product_name)
    elif category:
        products = Product.objects.filter(category__in=category)
    else:
        products = Product.objects.all()
        

    paginator = Paginator(products, 8)

    try:        
        page_number = request.GET.get('page')
        logger.info(f'Page: {page_number}')  # Log page number
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
        logger.error(f'User tried to open not integer page')  # Log error if page is not an integer
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
        logger.error(f'Page Not Found, Redirecting to {paginator.num_pages}')  # Log error if page is empty
    
    categories = Category.objects.all()
    category_by_type = {}
    
    for category in categories:
        category_type = category.category_type
        if category_type not in category_by_type:
            category_by_type[category_type] = []
        category_by_type[category_type].append(category)
    
    print(category_by_type)
    
    return render(request, 'index.html', {'products': products, 'categories_by_type': category_by_type})

@login_required(login_url='/users/login/')
def detail_product(request, pk):
    product = Product.objects.get(pk=pk)
    
    related_products = Product.objects.filter(category__in=product.category.all()).exclude(id=product.id)
    
    return render(request, 'detail_product.html', {'product': product, 'related_products': related_products})
    
def add_product(request):
    if request.user.has_perm('book_shope.add_product'):  # Check if user has permission
        if request.method == 'POST':
            form = ProductForm(request.POST,request.FILES)
            if form.is_valid():
                product = form.save(commit=False)
                product.save()
                form.save_m2m()
                return redirect('book_shope:index')
        else:
            form = ProductForm()
            return render(request, 'add_product.html', {'form': form})
    else:
        return redirect('book_shope:index')  # Redirect if user does not have permission

shope/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Category, Product
from .forms import ProductForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
import logging

from django.views.generic import TemplateView, DetailView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin



logger = logging.getLogger(__name__)  
# Create your views here.
def index(request):
    product_name = request.GET.get('product_name')
    category = request.GET.getlist('category')

    if product_name:
        products = Product.objects.filter(name__icontains=product_name)
    elif category:
        products = Product.objects.filter(category__in=category)
    else:
        products = Product.objects.all().order_by('name')  # Order by 'name' or any other field

    paginator = Paginator(products, 8)

    try:
        page_number = request.GET.get('page')
        logger.info(f'Page: {page_number}')
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
        logger.error(f'User tried to open not integer page')
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
        logger.error(f'Page Not Found, Redirecting to {paginator.num_pages}')

    categories = Category.objects.all()
    category_by_type = {}

    for category in categories:
        category_type = category.category_type
        if category_type not in category_by_type:
            category_by_type[category_type] = []
        category_by_type[category_type].append(category)

    cart_item_count = request.session.get('cart_item_count', 0)
    return render(request, 'index.html', {
        'products': products,
        'categories_by_type': category_by_type,
        'cart_item_count': cart_item_count
    })


class IndexView(TemplateView):
    template_name = 'index.html'
    
    def get(self, request, *args, **kwargs):
            product_name = request.GET.get('product_name')
            category = request.GET.getlist('category')
        
            if product_name:
                products = Product.objects.filter(name__icontains=product_name)
            elif category:
                products = Product.objects.filter(category__in=category)
            else:
                products = Product.objects.all()
                

            paginator = Paginator(products, 8)

            try:        
                page_number = request.GET.get('page')
                logger.info(f'Page: {page_number}')  
                products = paginator.page(page_number)
            except PageNotAnInteger:
                products = paginator.page(1)
                logger.error(f'User tried to open not integer page')  
            except EmptyPage:
                products = paginator.page(paginator.num_pages)
                logger.error(f'Page Not Found, Redirecting to {paginator.num_pages}')  
            
            categories = Category.objects.all()
            category_by_type = {}
            
            for category in categories:
                category_type = category.category_type
                if category_type not in category_by_type:
                    category_by_type[category_type] = []
                category_by_type[category_type].append(category)
            
            cart_item_count = request.session.get('cart_item_count', 0)
            return render(request, self.template_name, {
                'products': products,
                'category_by_type': category_by_type,
                'cart_item_count': cart_item_count,
            })
            print(category_by_type)
            
            return render(request, self.template_name, {'products': products, 'categories_by_type': category_by_type})




@login_required(login_url='/users/login/')
def detail_product(request, pk):
    product = Product.objects.get(pk=pk)
    related_products = Product.objects.filter(category__in=product.category.all()).exclude(id=product.id)[:4]
    return render(request, 'detail_product.html', {'product': product, 'related_products': related_products})
    
    
class ProductDetailView(DetailView):
    template_name = 'detail_product.html'
    context_object_name = 'product'
    model = Product 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        related_products = Product.objects.filter(category__in=product.category.all()).exclude(id=product.id)[:4]
        print(f'Context Before related_products: {context}')
        context['related_products'] = related_products
        print(f'Context After related_products: {context}')
        return context 


    
def add_product(request):
    if request.user.has_perm('shope.add_product'):  
        if request.method == 'POST':
            form = ProductForm(request.POST,request.FILES)
            if form.is_valid():
                product = form.save(commit=False)
                product.save()
                form.save_m2m()
                return redirect('shope:index')
        else:
            form = ProductForm()
            return render(request, 'add_product.html', {'form': form})
    else:
        return redirect('shope:index') 
#

class AddProductView(FormView):
    form_class = ProductForm
    template_name = 'Add_Product.html'
    success_url = reverse_lazy('shope:index-cbv')
    def form_valid(self, form):
        product = form.save(commit=False)
        product.save()
        form.save_m2m()
        return super().form_valid(form)
    def form_invalid(self, form):
        return super().form_invalid(form)

shope/templates/add_product.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'shope/css/add_product.css' %}">

    <form method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}

        <button type='submit' class="custom-class">Add</button>

        <a class='btn btn-danger' href='{% url "shope:index" %}'>Cancel</a>
    </form>
{% endblock %}

shope/templates/book_shope.html
{% for book in books %}
    
    <div class="card" style="width: 18rem; margin:10px">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Name: {{ product.name }}</h5>
            <p class="card-text">price: ${{ product.price }}</p>
            <p class="card-text">Categories: <span class='badge text-bg-secondary'>{{ product.category.all|join:', ' }}</span></p>
            <p class="card-text">Description: {{ product.description|truncatewords:20 }}</p>
            <a href="#" class="btn btn-primary">Add to Card</a>
        </div>
    </div>

{% endfor %}
    

shope/templates/category_filter.html
<form method="get" id="categoryFilterForm">
    <div class="d-flex flex-wrap justify-content-between">
        {% for category_type, category_by_type in categories_by_type.items %}
        <div style="width:6rem; height:auto; display:flex; flex-direction: column; justify-content: center; align-items: center; margin-bottom: 1rem;">
            <h3 style="font-size:0.90rem;">{{ category_type }}</h3>
            {% for category in category_by_type %}
            <div class="p-2">
                <input 
                    type="checkbox" 
                    name="category" 
                    value="{{ category.id }}" 
                    {% if category.id|stringformat:"s" in selected_categories %}checked{% endif %}
                    onchange="document.getElementById('categoryFilterForm').submit();">
                <label style="font-size:0.75rem;">{{ category.name }}</label>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</form>

shope/templates/detail_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="product-image">
                {% if product.picture %}
                    <img src="{{ product.picture.url }}" class="card-img-top product-img" alt="...">
                {% else %}
                    <img src="https://img.freepik.com/premium-photo/book-with-question-mark_1029469-140806.jpg" class="card-img-top product-img" alt="...">
                {% endif %}
            </div>
        </div>

        <div class="col-md-6">
            <h1 class="product-name">{{ product.name }}</h1>
            <h4 class="text-muted">Price: ${{ product.price }}</h4>

            <p class="product-stock text-success">
                {% if not product.stock %} 
                    <p class="card-text product-stock text-danger">Out Of Stock</p> 
                {% else %} 
                    <p class="card-text product-stock text-success">In Stock</p> 
                {% endif %}
            </p>

            <p class="mt-4">{{ product.description }}</p>

            <p><strong>Categories:</strong> {{ product.category.all|join:", " }}</p>

            <div class="d-grid gap-2 mt-4">
                <a class="btn btn-lg btn-primary" href="{% url 'orders:add_cart_item' product.id %}">Add to Cart</a>
            </div>
        </div>
    </div>

    {% if related_products %}
    <div class="related-products mt-5">
        <h3>Related Products</h3>
        <div class="row">
            {% for related_product in related_products %}
            <div class="col-md-3">

                <div class="card mb-4">

                    {% if related_product.image %}
                        <img src="{{  related_product.image.url }}" class="card-img-top" alt="{{ related_product.name }}">
                    {% else %}
                        <img src="" class="card-img-top" alt="No image available">
                    {% endif %}
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ related_product.name }}</h5>
                        <p class="card-text">${{ related_product.price }}</p>
                        <a href="{% url 'shope:detail_product' related_product.id %}" class="btn btn-outline-primary btn-sm">View Details</a>
                    </div>

                </div>

            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

shope/templates/index.html
{% extends 'base.html' %}

{% block title %} Health Main Page {% endblock %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    {% if perms.shope.add_product %}
        <a class='btn btn-primary my-3' href='{% url "shope:add_product" %}'>Add New Product</a>
    {% endif %}

    <div class="cont-main-size" >
        <div class="row">
            
            <div class="col-lg-2 col-md-3;">
                {% include 'category_filter.html' %}
            </div>
            
            
            <div class="col-lg-9 col-md-17">
                <div class="row">
                    {% include 'products.html' %}
                </div>
                {% include 'paginator.html' %}
            </div>
        </div>
    </div>
{% endblock %}

shope/templates/paginator.html
<ul class="pagination">

    {% if products.has_previous %}
        <li class="page-item">
            <a class="page-link" href='?page={{ products.previous_page_number }}'>Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" >Previous</a>
        </li>
    {% endif %}

    {% for num in products.paginator.page_range %}

        {% if products.number == num %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ num }}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endif %}

    {% endfor %}

    {% if products.has_next %}
        <li class="page-item">
                <a class="page-link" href='?page={{ products.next_page_number }}'>Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
                <a class="page-link" href='' >Next</a>
        </li>
    {% endif %}
</ul>

shope/templates/products.html
{% load static %}

{% for product in products %}

    <link rel="stylesheet" href="{% static 'css/products.css' %}"/>

    <div class="product-card">
        {% if product.picture %}
            <img src="{{ product.picture.url }}" class="card-img-top product-img" alt="...">
        {% else %}
            <img src="https://img.freepik.com/premium-photo/book-with-question-mark_1029469-140806.jpg" class="card-img-top product-img" alt="...">
        {% endif %}
        <div class="card-main-body">
            <div class="card-horizontal-body">
                <div class="small-infos-container">
                    
                    <div class='cont-small1'>
                        <h5 class="product-title">{{ product.name }}</h5>
                        <p class="product-info small-size1">Categories: <span class="badge text-bg-secondary">{{ product.category.all|join:", " }}</span></p>
                        <p class="product-price">${{ product.price }}</p>
                    </div>
                    
                    <div class="cont-small1">
                        <p class="product-info">Calories: {{ product.calories }}</p>
                        <p class="product-info">Protein: {{ product.protein }}</p>
                        <p class="product-info">Spiciness Rate: {{ product.spiciness_level }}</p>
                        <p class="product-info">Rating: {{ product.spiciness_level }}</p>
                    </div>

                </div>            
                <a href="{% url 'shope:detail_product' product.id %}" class="no-underline"> 
                    <p class="card-text product-description">{{ product.description|truncatewords:25 }}</p> 
                </a>
            </div>
            <div class="back">
                {% if not product.stock %} 
                        <p class="card-text product-stock text-danger">Out Of Stock</p> 
                {% else %} 
                    <p class="card-text product-stock text-success">In Stock</p> 
                {% endif %}

                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'orders:add_cart_item' product.id %}" id="add-cart-form-{{ product.id }}" class="add-cart-form">
                        {% csrf_token %}
                        <button type="button" class="btn btn-sm btn-outline-primary" onclick="submitForm('{{ product.id }}')">Add to Cart</button>
                    </form>
                {% endif %}
                {% comment %} <a href="{% url 'shope:detail_product' product.id %}" class="btn btn-sm btn-primary">View Details</a> {% endcomment %}
            </div>
        </div>
    </div>
{% endfor %}

<script>
    function submitForm(productId) {
        const form = document.getElementById(`add-cart-form-${productId}`);
        const formData = new FormData(form);
        const url = form.action;
    
        fetch(url, {
            method: 'POST',
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'X-CSRFToken': formData.get('csrfmiddlewaretoken')
            },
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                alert(data.message);  // You can replace this with your custom alert or update the page dynamically
                document.querySelector('.badge.badge-primary').textContent = data.cart_item_count;  // Update cart item count in the navbar
            } else {
                alert(data.message);  // Handle error message
            }
        });
    }
</script>